export type UiLanguage = 'en' | 'bn'

export function readUiLanguage(value: string | null): UiLanguage {
  return value === 'bn' ? 'bn' : 'en'
}

// Add or edit interface labels here. Keep the English key identical to the
// string passed to uiText() in a component; preserve {placeholder} names.
const bangla: Record<string, string> = {
  'READ DEEPLY': 'গভীরভাবে পড়ুন',
  'Reader controls': 'পাঠের নিয়ন্ত্রণ',
  '500 verbs': '৫০০টি ক্রিয়াপদ',
  'Open 500 verbs library': '৫০০ ক্রিয়াপদের তালিকা খুলুন',
  'Verbs': 'ক্রিয়াপদ',
  'Verb': 'ক্রিয়াপদ',
  'Saved': 'সংরক্ষিত',
  'Saved words, {count}': 'সংরক্ষিত শব্দ: {count}',
  'Display': 'প্রদর্শন',
  'Display settings': 'প্রদর্শনের সেটিংস',
  'Reading display': 'পাঠের প্রদর্শন',
  'Close display settings': 'প্রদর্শনের সেটিংস বন্ধ করুন',
  'Interface language': 'ইন্টারফেসের ভাষা',
  'Meanings to show': 'যেসব অর্থ দেখাবেন',
  'Both': 'উভয়',
  'Theme': 'থিম',
  'System': 'সিস্টেম',
  'Light': 'উজ্জ্বল',
  'Dark': 'অন্ধকার',
  'Text size': 'লেখার আকার',
  'Arabic verse size': 'আরবি আয়াতের আকার',
  '{count} percent': '{count} শতাংশ',
  'Only the Arabic ayah text and opening basmalah.': 'শুধু আরবি আয়াত ও শুরুতে থাকা বিসমিল্লাহর জন্য।',
  'Reading content': 'পাঠের বিষয়বস্তু',
  'Arabic verses': 'আরবি আয়াত',
  'Word-by-word meanings': 'শব্দে শব্দে অর্থ',
  'Highlight verbs': 'ক্রিয়াপদ চিহ্নিত করুন',
  'Verb study meanings': 'ক্রিয়াপদের অধ্যয়নের অর্থ',
  'বাংলা book meanings': 'বইয়ের বাংলা অর্থ',
  'English Quran example': 'কুরআনের ইংরেজি উদাহরণ',
  'Offline reading': 'অফলাইনে পড়া',
  'Save all surahs, word meanings, verb study, and the 500-verb library on this device. Audio and external links still need internet.': 'সব সূরা, শব্দের অর্থ, ক্রিয়াপদের অধ্যয়ন এবং ৫০০ ক্রিয়াপদের তালিকা এই ডিভাইসে সংরক্ষণ করুন। অডিও ও বাইরের লিংকের জন্য ইন্টারনেট লাগবে।',
  'About {count} MB on this device.': 'এই ডিভাইসে প্রায় {count} এমবি জায়গা লাগবে।',
  'Save for offline use': 'অফলাইনে ব্যবহারের জন্য সংরক্ষণ করুন',
  'Saved for offline use': 'অফলাইনে ব্যবহারের জন্য সংরক্ষিত',
  'Saving offline files…': 'অফলাইন ফাইল সংরক্ষিত হচ্ছে…',
  'Retry offline save': 'অফলাইন সংরক্ষণ আবার চেষ্টা করুন',
  'Offline save progress': 'অফলাইন সংরক্ষণের অগ্রগতি',
  'All reading and study files are saved on this device.': 'পড়া ও অধ্যয়নের সব ফাইল এই ডিভাইসে সংরক্ষিত।',
  'Offline save stopped. Reconnect and retry; saved files will be reused.': 'অফলাইন সংরক্ষণ থেমেছে। সংযোগ চালু করে আবার চেষ্টা করুন; আগের সংরক্ষিত ফাইলগুলো ব্যবহার করা হবে।',
  '{saved} of {total} files saved. Keep this page open.': '{total}টির মধ্যে {saved}টি ফাইল সংরক্ষিত। পৃষ্ঠাটি খোলা রাখুন।',
  'Checking offline files…': 'অফলাইন ফাইল পরীক্ষা করা হচ্ছে…',
  'Save once while online before reading without a connection.': 'ইন্টারনেট থাকাকালে একবার সংরক্ষণ করলে পরে সংযোগ ছাড়াই পড়তে পারবেন।',
  'Saved words': 'সংরক্ষিত শব্দ',
  'Close saved words': 'সংরক্ষিত শব্দের তালিকা বন্ধ করুন',
  'Tap “Save word” while studying to keep it here.': 'অধ্যয়নের সময় “শব্দ সংরক্ষণ” চাপলে এখানে জমা থাকবে।',
  'Open surah sidebar': 'সূরার পাশের তালিকা খুলুন',
  'Close surah sidebar': 'সূরার পাশের তালিকা বন্ধ করুন',
  'Chapter navigation': 'সূরা নির্বাচন',
  'EXPLORE THE QURAN': 'কুরআন অন্বেষণ করুন',
  'Surahs': 'সূরাসমূহ',
  'Find a surah': 'সূরা খুঁজুন',
  '{count} ayahs': '{count}টি আয়াত',
  'Every word has a place to explore.': 'প্রতিটি শব্দই অধ্যয়নের সুযোগ।',
  'Close chapter list': 'সূরার তালিকা বন্ধ করুন',
  'Current reading location': 'বর্তমান পাঠের অবস্থান',
  'Choose Surah': 'সূরা নির্বাচন করুন',
  'Surah {number}': 'সূরা {number}',
  'Ayah {key}': 'আয়াত {key}',
  'THE QURAN': 'আল-কুরআন',
  'SURAH {number}': 'সূরা {number}',
  'CHAPTER {number}': 'সূরা {number}',
  'A word-by-word grammar journey': 'শব্দে শব্দে ব্যাকরণ অধ্যয়ন',
  'Choose surah': 'সূরা নির্বাচন করুন',
  'Verb highlighted': 'ক্রিয়াপদ চিহ্নিত',
  'Tap any word to study': 'অধ্যয়নের জন্য যেকোনো শব্দ চাপুন',
  'Could not load the chapter list. Reconnect and try again.': 'সূরার তালিকা লোড হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  'Retry chapter list': 'সূরার তালিকা আবার চেষ্টা করুন',
  'This chapter could not load. Reconnect and try again.': 'এই সূরা লোড হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  'Retry chapter': 'সূরাটি আবার চেষ্টা করুন',
  'Opening the chapter…': 'সূরা খোলা হচ্ছে…',
  'Previous surah': 'আগের সূরা',
  'Next surah': 'পরের সূরা',
  'Sources & credits': 'উৎস ও স্বীকৃতি',
  'Reciter': 'তিলাওয়াতকারী',
  'Play recitation {key}': '{key} আয়াতের তিলাওয়াত শুনুন',
  'Pause recitation {key}': '{key} আয়াতের তিলাওয়াত থামান',
  'Recite': 'তিলাওয়াত',
  'Pause': 'থামান',
  'Audio requires an internet connection.': 'অডিও শুনতে ইন্টারনেট সংযোগ প্রয়োজন।',
  'Audio is unavailable for this location.': 'এই স্থানের অডিও পাওয়া যায়নি।',
  'Audio could not load. Check your connection and try again.': 'অডিও লোড হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  'Audio could not play. Check your connection and try again.': 'অডিও চালু হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  'Word audio uses a separate recording from Quran Foundation.': 'শব্দের অডিও কুরআন ফাউন্ডেশনের পৃথক রেকর্ডিং।',
  'Study {word}, word {position}': '{position} নম্বর শব্দ {word} অধ্যয়ন করুন',
  'Word study': 'শব্দ অধ্যয়ন',
  'WORD STUDY': 'শব্দ অধ্যয়ন',
  'A closer look': 'আরও গভীরে দেখুন',
  'Close study panel': 'অধ্যয়নের প্যানেল বন্ধ করুন',
  'বাংলা অর্থ': 'বাংলা অর্থ',
  'ENGLISH MEANING': 'ইংরেজি অর্থ',
  'ENGLISH': 'ইংরেজি',
  'Verb grammar summary': 'ক্রিয়াপদের ব্যাকরণ সংক্ষেপ',
  'Save word': 'শব্দ সংরক্ষণ',
  'View in ayah': 'আয়াতে দেখুন',
  'Hear word': 'শব্দ শুনুন',
  'Pause word': 'শব্দ থামান',
  'Grammar identity': 'ব্যাকরণ পরিচয়',
  'WORD TYPE': 'শব্দের ধরন',
  'ROOT · الجذر': 'ধাতু · الجذر',
  'Not assigned': 'নির্ধারিত নয়',
  'See original morphology tags': 'মূল রূপতাত্ত্বিক চিহ্ন দেখুন',
  'Loading this verb’s examples and conjugations…': 'ক্রিয়াপদের উদাহরণ ও রূপ লোড হচ্ছে…',
  'This verb’s study data could not load. Word meanings remain available.': 'এই ক্রিয়াপদের অধ্যয়নের তথ্য লোড হয়নি। শব্দের অর্থ দেখা যাবে।',
  'Try again': 'আবার চেষ্টা করুন',
  'Explore this verb': 'এই ক্রিয়াপদ অধ্যয়ন করুন',
  'SELECTED VERB FORM': 'নির্বাচিত ক্রিয়ার রূপ',
  'Form {form}': 'রূপ {form}',
  'Passive examples': 'কর্মবাচ্যের উদাহরণ',
  'Active examples': 'কর্তৃবাচ্যের উদাহরণ',
  'FORM PATTERN · HE': 'রূপের ছাঁচ · সে',
  'THIS VERB · HE': 'এই ক্রিয়াপদ · সে',
  'Past': 'অতীত',
  'Present / future': 'বর্তমান / ভবিষ্যৎ',
  'Command': 'আদেশ',
  'Who': 'পুরুষ',
  'Active teaching pattern': 'কর্তৃবাচ্যের শিক্ষণীয় ছাঁচ',
  'Passive': 'কর্মবাচ্য',
  'Active': 'কর্তৃবাচ্য',
  'QURAN EXAMPLE': 'কুরআনের উদাহরণ',
  'No matching occurrence': 'মিলে যাওয়া ব্যবহার নেই',
  'বাংলা: matching book forms. English: linked Quran examples, whose meaning depends on context. Meanings appear only where a source matches.': 'বাংলা: বইয়ের মিলে যাওয়া রূপ। ইংরেজি: সংযুক্ত কুরআনের উদাহরণ, যার অর্থ প্রসঙ্গভেদে বদলায়। উৎসে মিল থাকলেই অর্থ দেখানো হয়।',
  'What does Form {form} mean?': '{form} রূপের অর্থ কী?',
  'A form suggests a common pattern of meaning; the actual sense depends on the verb and its context.': 'একটি রূপ অর্থের সাধারণ ধারা বোঝায়; প্রকৃত অর্থ ক্রিয়াপদ ও প্রসঙ্গের ওপর নির্ভর করে।',
  'Read the Corpus guide': 'করপাসের নির্দেশিকা পড়ুন',
  'Explain all ten three-letter forms': 'তিন অক্ষরের দশটি রূপ ব্যাখ্যা করুন',
  'These are teaching patterns. A root does not necessarily occur in every form.': 'এগুলো শেখার জন্য রূপের ছাঁচ। একটি ধাতু সব রূপে নাও থাকতে পারে।',
  'Source: Quranic Arabic Corpus': 'উৎস: কুরআনিক আরবি করপাস',
  'Compare patterns': 'রূপের ছাঁচ তুলনা করুন',
  'Voice': 'বাচ্য',
  'Verb study view': 'ক্রিয়াপদ অধ্যয়নের দৃশ্য',
  'Quran examples': 'কুরআনের উদাহরণ',
  'Full pattern': 'পূর্ণ রূপের ছাঁচ',
  'Full conjugation': 'পূর্ণ ক্রিয়ারূপ',
  'In the Quran': 'কুরআনে ব্যবহার',
  'Show feminine & dual': 'স্ত্রীলিঙ্গ ও দ্বিবচন দেখান',
  'Hide feminine & dual': 'স্ত্রীলিঙ্গ ও দ্বিবচন লুকান',
  'Show book chart · বাংলা': 'বইয়ের ছক দেখান · বাংলা',
  'Show all Arabic persons · feminine & dual': 'সব আরবি পুরুষ দেখান · স্ত্রীলিঙ্গ ও দ্বিবচন',
  'Show all {count} occurrences': 'সব {count}টি ব্যবহার দেখান',
  'Not attested in this corpus': 'এই করপাসে পাওয়া যায়নি',
  'Not applicable': 'প্রযোজ্য নয়',
  '{count} occurrences': '{count}টি ব্যবহার',
  'Exact written form': 'হুবহু লিখিত রূপ',
  'Root + form {form} + {voice}': 'ধাতু + রূপ {form} + {voice}',
  'Verb root total': 'ধাতুর মোট ব্যবহার',
  'VERB FORM · بَاب': 'ক্রিয়ার রূপ · بَاب',
  'Corpus classification': 'করপাসের শ্রেণিবিন্যাস',
  'ASPECT': 'কাল',
  'PERSON': 'পুরুষ',
  'VOICE': 'বাচ্য',
  'Mood: {mood}': 'ভাব: {mood}',
  'Corpus annotation': 'করপাসের চিহ্ন',
  'View source details': 'উৎসের বিবরণ দেখুন',
  'Book {level}': 'বই {level}',
  'Original page {page}': 'মূল পৃষ্ঠা {page}',
  'Source page {page}': 'উৎস পৃষ্ঠা {page}',
  'Conjugation table; scroll horizontally for all columns': 'ক্রিয়ারূপের ছক; সব কলাম দেখতে পাশে স্ক্রল করুন',
  'Not supplied in this book': 'এই বইয়ে দেওয়া নেই',
  'Bangla meaning hidden': 'বাংলা অর্থ লুকানো',
  'Check printed form': 'মুদ্রিত রূপ পরীক্ষা করুন',
  'Check source page {page}': 'উৎসের {page} নম্বর পৃষ্ঠা দেখুন',
  'Source & transcription notes': 'উৎস ও প্রতিলিপির নোট',
  'YOUR GRAMMAR COMPANION': 'আপনার ব্যাকরণ সহায়িকা',
  'Close verb library': 'ক্রিয়াপদের তালিকা বন্ধ করুন',
  'Find a book verb': 'বইয়ের ক্রিয়াপদ খুঁজুন',
  'Search 500 verbs': '৫০০ ক্রিয়াপদের মধ্যে খুঁজুন',
  'Book': 'বই',
  'Both levels': 'দুই স্তর',
  'Level {level}': 'স্তর {level}',
  'All forms': 'সব রূপ',
  '{count} of 500 verbs': '৫০০টির মধ্যে {count}টি ক্রিয়াপদ',
  'No matching verb.': 'মিলে যাওয়া ক্রিয়াপদ নেই।',
  'Clear filters': 'ফিল্টার মুছুন',
  'Root': 'ধাতু',
  'Two readings in the book': 'বইয়ে দুটি পাঠ আছে',
  'Read. Cover. Recall.': 'পড়ুন। ঢাকুন। মনে করুন।',
  'Hide meanings': 'অর্থ লুকান',
  'Show meanings': 'অর্থ দেখান',
  'Browse book verbs': 'বইয়ের ক্রিয়াপদ দেখুন',
  'Previous': 'আগেরটি',
  'Next': 'পরেরটি',
  'Current verb is outside your filters': 'বর্তমান ক্রিয়াপদটি ফিল্টারের বাইরে',
  'Reload app': 'অ্যাপ আবার লোড করুন',
  'Could not load {label}. Reconnect and try again.': '{label} লোড হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  'Opening {label}…': '{label} খোলা হচ্ছে…',
  'Close {label}': '{label} বন্ধ করুন',
  'Loading…': 'লোড হচ্ছে…',
  'Quran text: Tanzil · Verse translations: Saheeh International and Muhiuddin Khan · Grammar: Quranic Arabic Corpus · Word meanings: GTAF.': 'কুরআনের পাঠ: Tanzil · আয়াতের অনুবাদ: Saheeh International ও Muhiuddin Khan · ব্যাকরণ: Quranic Arabic Corpus · শব্দার্থ: GTAF।',
  'Verse audio: Al Quran Cloud / Islamic Network · Word audio: Quran Foundation.': 'আয়াতের অডিও: Al Quran Cloud / Islamic Network · শব্দের অডিও: Quran Foundation।',
  'Quran': 'কুরআন',
  'English in context: {word}': 'প্রসঙ্গভিত্তিক ইংরেজি অর্থ: {word}',
  'বাংলা: Book {level}, p. {page}': 'বাংলা: বই {level}, পৃষ্ঠা {page}',
  'Bangla conjugation meaning from the supplied verb list': 'সরবরাহকৃত ক্রিয়াপদের তালিকা থেকে বাংলা অর্থ',
  'Word study panel': 'শব্দ অধ্যয়নের প্যানেল',
  'Resize Quran and study panels': 'কুরআন ও অধ্যয়নের প্যানেলের আকার বদলান',
  'Form {form}: attested Quranic verb examples by person and aspect': 'রূপ {form}: পুরুষ ও কাল অনুযায়ী কুরআনে পাওয়া ক্রিয়ার উদাহরণ',
  'Full active reference conjugation for Form {form}, using the placeholder root {root}': 'রূপ {form}-এর পূর্ণ কর্তৃবাচ্য নমুনা ক্রিয়ারূপ; উদাহরণ ধাতু {root}',
  'Selected Quran word ({key}):': 'নির্বাচিত কুরআনের শব্দ ({key}):',
  'Full {voice} conjugation of {verb} · Form {form}': '{verb}-এর পূর্ণ {voice} ক্রিয়ারূপ · রূপ {form}',
  'active': 'কর্তৃবাচ্য',
  'passive': 'কর্মবাচ্য',
  'A reliable full conjugation is not available for this root and form yet. The Quran examples and reference pattern remain available.': 'এই ধাতু ও রূপের নির্ভরযোগ্য পূর্ণ ক্রিয়ারূপ এখনো নেই। কুরআনের উদাহরণ ও নমুনা ছক দেখা যাবে।',
  'Chart entries are Quranic word examples and contextual meanings. — means unattested here; n/a means the imperative does not apply to that person.': 'ছকে কুরআনের শব্দ ও প্রসঙ্গভিত্তিক অর্থ দেখানো হয়েছে। — মানে এখানে পাওয়া যায়নি; n/a মানে ওই পুরুষে আদেশরূপ প্রযোজ্য নয়।',
  'Reference conjugation of the placeholder root': 'উদাহরণ ধাতুর নমুনা ক্রিয়ারূপ',
  'generated with': 'তৈরি হয়েছে',
  'These are not Quranic word examples or verified conjugations of the selected root. Form I shows one standard vowel pattern; weak roots may conjugate differently.': 'এগুলো কুরআনের শব্দের উদাহরণ বা নির্বাচিত ধাতুর যাচাইকৃত ক্রিয়ারূপ নয়। প্রথম রূপে একটি প্রচলিত স্বরধারা দেখানো হয়েছে; দুর্বল ধাতুর রূপ ভিন্ন হতে পারে।',
  'Root-specific Arabic forms generated with': 'নির্দিষ্ট ধাতুর আরবি রূপ তৈরি হয়েছে',
  'from a Corpus-matched verb citation. Bangla meanings come from the two local verb books only where the root, form, voice, Arabic spelling, aspect, and person match this cell. The book covers common masculine and first-person forms; other cells remain Arabic only. See Quran examples for contextual word meanings.': 'করপাসে মিলে যাওয়া ক্রিয়ার মূল রূপ থেকে। বাংলা অর্থ শুধু তখনই দুইটি স্থানীয় ক্রিয়ার বই থেকে নেওয়া হয়েছে, যখন ধাতু, রূপ, বাচ্য, আরবি বানান, কাল ও পুরুষ এই ঘরের সঙ্গে মেলে। বইয়ে সাধারণ পুংলিঙ্গ ও উত্তম পুরুষের রূপ আছে; অন্য ঘরগুলো শুধু আরবি। প্রসঙ্গভিত্তিক অর্থের জন্য কুরআনের উদাহরণ দেখুন।',
  'Grammar: Quranic Arabic Corpus v0.4 · Meanings: GTAF word databases.': 'ব্যাকরণ: Quranic Arabic Corpus v0.4 · অর্থ: GTAF শব্দভান্ডার।',
  'Book conjugation {number}': 'বইয়ের {number} নম্বর ক্রিয়ারূপ',
  'Verb {number}': 'ক্রিয়াপদ {number}',
  'Book conjugation of {verb}, entry {number}; masculine and first-person forms': '{verb}-এর বইয়ের ক্রিয়ারূপ, ক্রমিক {number}; পুংলিঙ্গ ও উত্তম পুরুষের রূপ',
  'The book gives masculine and first-person forms. Feminine and dual forms are not supplied.': 'বইয়ে পুংলিঙ্গ ও উত্তম পুরুষের রূপ আছে। স্ত্রীলিঙ্গ ও দ্বিবচনের রূপ দেওয়া নেই।',
  '* An obvious printed Bangla typo has been corrected.': '* মুদ্রিত বাংলার একটি স্পষ্ট ভুল সংশোধন করা হয়েছে।',
  'Highlighted Arabic cells need checking against the printed source.': 'চিহ্নিত আরবি ঘরগুলো মুদ্রিত উৎসের সঙ্গে মিলিয়ে দেখা দরকার।',
  'Reference: Quran words, Level {level}, pages {pages}. The original books are not distributed with this app. Entry numbers and table completeness were checked, with targeted visual checks of the text. The entire collection has not been independently proofread. Consult your own copy when a form or meaning looks unusual.': 'উৎস: Quran words, স্তর {level}, পৃষ্ঠা {pages}। মূল বইগুলো এই অ্যাপের সঙ্গে বিতরণ করা হয় না। ক্রমিক নম্বর ও ছকের পূর্ণতা পরীক্ষা করা হয়েছে এবং লেখার কিছু অংশ চোখে মিলিয়ে দেখা হয়েছে। পুরো সংগ্রহটি স্বাধীনভাবে প্রুফরিড করা হয়নি। কোনো রূপ বা অর্থ অস্বাভাবিক মনে হলে নিজের বইয়ের কপি দেখুন।',
  'Form': 'রূপ',
  'Level 1 · 1–200': 'স্তর ১ · ১–২০০',
  'Level 2 · 201–500': 'স্তর ২ · ২০১–৫০০',
  'আরবি, বাংলা, or number…': 'আরবি, বাংলা অথবা নম্বর…',
  'The basic pattern. Its meaning comes mainly from the root; it may take an object or stand alone.': 'এটি মূল রূপ। অর্থ প্রধানত ধাতু থেকে আসে; এটি কর্ম নিতে পারে বা একাই থাকতে পারে।',
  'Often adds intensity, repetition, or a causative sense: making someone do the action.': 'প্রায়ই তীব্রতা, পুনরাবৃত্তি বা কাউকে কাজটি করানোর অর্থ যোগ করে।',
  'Often involves another participant, sometimes with a mutual or shared action.': 'প্রায়ই আরেকজন অংশগ্রহণকারী থাকে; কখনো পারস্পরিক বা যৌথ কাজ বোঝায়।',
  'Often makes an action causative or moves someone or something into a new state.': 'প্রায়ই কাউকে দিয়ে কাজ করানো বা কাউকে বা কিছুকে নতুন অবস্থায় নেওয়া বোঝায়।',
  'Related to Form II; often describes undergoing or doing the action to oneself.': 'দ্বিতীয় রূপের সঙ্গে সম্পর্কিত; প্রায়ই নিজের ওপর কাজ ঘটানো বা কাজটি নিজে করা বোঝায়।',
  'Related to Form III; often expresses a shared or reciprocal action.': 'তৃতীয় রূপের সঙ্গে সম্পর্কিত; প্রায়ই যৌথ বা পারস্পরিক কাজ বোঝায়।',
  'Often expresses undergoing an action or being affected by it.': 'প্রায়ই কোনো কাজের প্রভাব গ্রহণ করা বোঝায়।',
  'Often expresses a reflexive, deliberate, or reciprocal action.': 'প্রায়ই নিজের দিকে ফেরানো, ইচ্ছাকৃত বা পারস্পরিক কাজ বোঝায়।',
  'Usually describes becoming a color or acquiring a physical quality.': 'সাধারণত কোনো রঙ ধারণ করা বা শারীরিক বৈশিষ্ট্য অর্জন করা বোঝায়।',
  'Often expresses seeking something, asking for it, or causing a change.': 'প্রায়ই কিছু চাওয়া, তার অনুরোধ করা বা পরিবর্তন ঘটানো বোঝায়।',
  'The basic four-root-letter pattern.': 'চার অক্ষরের ধাতুর মূল রূপ।',
  'Often describes an action affecting the doer, related to the basic pattern.': 'মূল রূপের সঙ্গে সম্পর্কিত; প্রায়ই কর্তার ওপর কাজের প্রভাব বোঝায়।',
  'Usually describes undergoing a change or action.': 'সাধারণত পরিবর্তন বা কোনো কাজের প্রভাব গ্রহণ করা বোঝায়।',
  'Often describes entering or being in a state.': 'প্রায়ই কোনো অবস্থায় প্রবেশ করা বা সেই অবস্থায় থাকা বোঝায়।',
}

export function uiText(language: UiLanguage, english: string, values: Record<string, string | number> = {}): string {
  const template = language === 'bn' ? bangla[english] ?? english : english
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`))
}
